```{r}
mito1_up <- read.table("mito/mitodeg1_up.txt")
mito2_up <- read.table("mito/mitodeg2_up.txt")
mito3_up <- read.table("mito/mitodeg3_up.txt")
mito_up <- union(mito1_up$V1,mito2_up$V1)
mito_up <- union(mito_up,mito3_up$V1)
length(mito_up)
```
```{r}
write.table(mito_up,file ='mito/mito_up.txt',row.names = F,col.names = F,quote=F)
```

```{r}
mito1_down <- read.table("mito/mitodeg1_down.txt")
mito2_down <- read.table("mito/mitodeg2_down.txt")
mito3_down <- read.table("mito/mitodeg3_down.txt")
mito_down <- union(mito1_down$V1,mito2_down$V1)
mito_down <- union(mito_down,mito3_down$V1)
length(mito_down)
```
```{r}
write.table(mito_down,file ='mito/mito_down.txt',row.names = F,col.names = F,quote=F)
```

https://bioinfogp.cnb.csic.es/tools/venny/index.html
Venn图作图软件

我们思考到一个问题就是数据集应该满足交在deg上

所以我们要看up和down的deg是啥

up
```{r}
library(readr)
upGene_1_0_05 <- read_csv("deg1/upGene_1_0.05.csv")
deg_up1 <- upGene_1_0_05$...1
upGene_1_0_05 <- read_csv("deg2/upGene_1_0.05.csv")
deg_up2 <- upGene_1_0_05$...1
upGene_1_0_05 <- read_csv("deg3/upGene_1_0.05.csv")
deg_up3 <- upGene_1_0_05$...1
```
取交集
```{r}
deg_up <- intersect(deg_up1,deg_up2)
deg_up <- intersect(deg_up,deg_up3)
deg_up
```
```{r}
library(readr)
downGene_1_0_05 <- read_csv("deg1/downGene_1_0.05.csv")
deg_down1 <- downGene_1_0_05$...1
downGene_1_0_05 <- read_csv("deg2/downGene_1_0.05.csv")
deg_down2 <- downGene_1_0_05$...1
downGene_1_0_05 <- read_csv("deg3/downGene_1_0.05.csv")
deg_down3 <- downGene_1_0_05$...1
deg_down <- intersect(deg_down1,deg_down2)
deg_down <- intersect(deg_down,deg_down3)
deg_down
```

