```{r}
load("./data/DESeq2_raw.Rdata")
dim(DEG)
```

```{r}
DEG$g=ifelse(DEG$pvalue>0.05,'stable', 
            ifelse( DEG$log2FoldChange >1,'up', 
                    ifelse( DEG$log2FoldChange < -1,'down','stable') )
)
table(DEG$g)
```

```{r}
deg_up <- DEG[DEG$g=="up",]
deg_down <- DEG[DEG$g=="down",]
```

# UPGENE
```{r}
#???ð?
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(org.Rn.eg.db)
library(enrichplot)
library(ggplot2)
library(circlize)
library(RColorBrewer)
library(dplyr)
library("ggpubr")
library(ComplexHeatmap)

pvalueFilter=0.05      #pֵ????????
qvalueFilter=1         #????????pֵ????????
# inputFile="interGenes.txt"     #???????????б??ļ?

#????ͼ?ε???ɫ
colorSel="qvalue"
if(qvalueFilter>0.05){
	colorSel="pvalue"
}

rt <- deg_up
genes <- unique(as.vector(rownames(rt)))
entrezIDs=mget(genes, org.Hs.egSYMBOL2EG, ifnotfound=NA)
entrezIDs=as.character(entrezIDs)
gene=entrezIDs[entrezIDs!="NA"]        #ȥ??????idΪNA?Ļ???
#gene=gsub("c\\(\"(\\d+)\".*", "\\1", gene)
```

```{r}
#GO????????
kk=enrichGO(gene=gene, OrgDb="org.Hs.eg.db", pvalueCutoff=0.05, qvalueCutoff=1, ont="all", readable=T)
GO=as.data.frame(kk)
GO=GO[(GO$pvalue<pvalueFilter & GO$qvalue<qvalueFilter),]
#?????????????Ľ???
write.table(GO, file="data/GO_UP.txt", sep="\t", quote=F, row.names = F)
```

```{r}
#??״ͼ
pdf(file="Figure2/barplot_up.pdf", width=9, height=7)
bar=barplot(kk, drop=TRUE, showCategory=10, label_format=130, split="ONTOLOGY", color=colorSel) + facet_grid(ONTOLOGY~., scale='free')
print(bar)
dev.off()
		
#????ͼ
pdf(file="Figure2/bubble_up.pdf", width=9, height=7)
bub=dotplot(kk, showCategory=10, orderBy="GeneRatio", label_format=130, split="ONTOLOGY", color=colorSel) + facet_grid(ONTOLOGY~., scale='free')
print(bub)
dev.off()
```
```{r}
############## 富集分析分组柱状图 ##################
library(dplyr)
ego <- kk

# 先根据BP、CC和MF按照q值选出前10个GO出来用于画图：用by实现
ego_filter <- by(ego, ego$ONTOLOGY, function(x) arrange(x, x[,8])[1:10,])
ego <- rbind(ego_filter$BP,ego_filter$CC,ego_filter$MF)

# 将数据按照ONTOLOGY分组，并按gene数目排序：
bp <- ego[which(ego$ONTOLOGY %in% "BP"),]
newbp <- arrange(bp, bp[,10])

cc <- ego[which(ego$ONTOLOGY %in% "CC"),]
newcc <- arrange(cc, cc[,10])

mf <- ego[which(ego$ONTOLOGY %in% "MF"),]
newmf <- arrange(mf, mf[,10])

go_enrich_df <- rbind(newbp,newcc,newmf)

# 如果我们熟练掌握apply系列函数的话，上面的过程完全可以用by快速实现；
go_list <- by(ego, ego$ONTOLOGY, function(x) arrange(x, x[,10]))
go_enrich_df2 <- rbind(go_list$BP,go_list$CC,go_list$MF)

go_enrich_df$number <- factor(rev(1:nrow(go_enrich_df)))

shorten_names <- function(x, n_word=10, n_char=40){
   if (length(strsplit(x, " ")[[1]]) > n_word || (nchar(x)>n_char))
     {
           if (nchar(x) >n_char) x <- substr(x, 1, n_char)
           x <- paste(paste(strsplit(x, " ")[[1]][1:min(length(strsplit(x," ")[[1]]), n_word)],
                                                                                collapse=" "), "...", sep="")
           return(x)
         } 
   else
     {
           return(x)
         }
}

# labels=(sapply(
#    levels(go_enrich_df$Description)[as.numeric(go_enrich_df$Description)],
#    shorten_names))

labels <- (sapply(
  go_enrich_df$Description,shorten_names
))

labels
```


```{r}
# 排序：
#  rev(1:nrow(go_enrich_df)) 的作用是生成一个逆序的序列，范围从 1 到 go_enrich_df 数据框的行数。换句话说，它创建了一个从 go_enrich_df 的最后一行到第一行的递减序列。
names(labels) = rev(1:nrow(go_enrich_df))
CPCOLS <- c('#e6b707', '#99c355', '#4cace9')

library(ggplot2)

# 垂直版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_bar(stat="identity", width=0.8) + coord_flip() + 
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text=element_text(face = "plain"))+
  theme(axis.text.y=element_text(color=rep(rev(CPCOLS),rep(10,3)))) + 
  theme(legend.title=element_blank())

ggsave("./Figure2/vetical_GO_plot_up.pdf", height = 10,width = 8)

# 水平版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_bar(stat="identity", width=0.8) +
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text =element_text(face = "plain")) + 
  theme(axis.text.x=element_text(angle=70, hjust = 1, color=rep(rev(CPCOLS),rep(10,3)))) + 
  theme(legend.title=element_blank(),legend.position = "top")

ggsave("./Figure2/horizontal_GO_plot_up.pdf", height = 6.5,width = 10)

################# 同样也可以绘制分组气泡图 ##################3
# 垂直版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_point(aes(size=-log10(qvalue)), shape=21, stat="identity") + coord_flip() + 
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text=element_text(face = "plain"))+
  theme(axis.text.y=element_text(color=rep(rev(CPCOLS),rep(10,3)))) + 
  theme(legend.title=element_blank())

ggsave("Figure2/vetical_GO_buble_plot_up.pdf", height = 10,width = 8)

# 水平版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_point(aes(size=-log10(qvalue)), shape=21, stat="identity") +
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text =element_text(face = "plain")) + 
  theme(axis.text.x=element_text(angle=70, hjust = 1, color=rep(rev(CPCOLS),rep(10,3)))) + 
  guides(size=guide_legend("-log10(qvalue)"),
                 fill=guide_legend("ONTOLOGY"))+
  theme(legend.text = element_text(vjust = 0.5))

ggsave("Figure2/horizontal_GO_buble_plot_up.pdf", height = 6.5,width = 10)
```


```{r}
###########????GOȦͼ###########

ontology.col=c("#5F559BFF", "#008B45FF", "#FD8CC1FF")
ontology.col=c("#2874C5","#f87669","#e6b707")
ontology.col=c("#f0d182", "#c4d78b", "#80bbd9")
ontology.col=c('#e6b707', '#99c355', '#4cace9')
data=GO[order(GO$p.adjust),]
datasig=data[data$pvalue<0.05,,drop=F]
BP = datasig[datasig$ONTOLOGY=="BP",,drop=F]
CC = datasig[datasig$ONTOLOGY=="CC",,drop=F]
MF = datasig[datasig$ONTOLOGY=="MF",,drop=F]
BP = head(BP,6)
CC = head(CC,6)
MF = head(MF,6)
data = rbind(BP,CC,MF)
main.col = ontology.col[as.numeric(as.factor(data$ONTOLOGY))]

#????Ȧͼ????
BgGene = as.numeric(sapply(strsplit(data$BgRatio,"/"),'[',1))
Gene = as.numeric(sapply(strsplit(data$GeneRatio,'/'),'[',1))
ratio = Gene/BgGene
logpvalue = -log(data$pvalue,10)
logpvalue.col = brewer.pal(n = 8, name = "Reds")
f = colorRamp2(breaks = c(0,2,4,6,8,10,15,20), colors = logpvalue.col)
BgGene.col = f(logpvalue)
df = data.frame(GO=data$ID,start=1,end=max(BgGene))
rownames(df) = df$GO
bed2 = data.frame(GO=data$ID,start=1,end=BgGene,BgGene=BgGene,BgGene.col=BgGene.col)
bed3 = data.frame(GO=data$ID,start=1,end=Gene,BgGene=Gene)
bed4 = data.frame(GO=data$ID,start=1,end=max(BgGene),ratio=ratio,col=main.col)
bed4$ratio = bed4$ratio/max(bed4$ratio)*9.5

#????Ȧͼ?????岿??
pdf(file="Figure2/GO.circlize_up.pdf", width=10, height=10)
par(omi=c(0.1,0.1,0.1,1.5))
circos.par(track.margin=c(0.01,0.01))
circos.genomicInitialize(df,plotType="none")
circos.trackPlotRegion(ylim = c(0, 1), panel.fun = function(x, y) {
  sector.index = get.cell.meta.data("sector.index")
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  circos.text(mean(xlim), mean(ylim), sector.index, cex = 0.8, facing = "bending.inside", niceFacing = TRUE)
}, track.height = 0.08, bg.border = NA,bg.col = main.col)

for(si in get.all.sector.index()) {
  circos.axis(h = "top", labels.cex = 0.6, sector.index = si,track.index = 1,
              major.at=seq(0,max(BgGene),by=100),labels.facing = "clockwise")
}
f = colorRamp2(breaks = c(-1, 0, 1), colors = c("green", "black", "red"))
circos.genomicTrack(bed2, ylim = c(0, 1),track.height = 0.1,bg.border="white",
                    panel.fun = function(region, value, ...) {
                      i = getI(...)
                      circos.genomicRect(region, value, ytop = 0, ybottom = 1, col = value[,2], 
                                         border = NA, ...)
                      circos.genomicText(region, value, y = 0.4, labels = value[,1], adj=0,cex=0.8,...)
                    })
circos.genomicTrack(bed3, ylim = c(0, 1),track.height = 0.1,bg.border="white",
                    panel.fun = function(region, value, ...) {
                      i = getI(...)
                      circos.genomicRect(region, value, ytop = 0, ybottom = 1, col = '#BA55D3', 
                                         border = NA, ...)
                      circos.genomicText(region, value, y = 0.4, labels = value[,1], cex=0.9,adj=0,...)
                    })
circos.genomicTrack(bed4, ylim = c(0, 10),track.height = 0.35,bg.border="white",bg.col="grey90",
                    panel.fun = function(region, value, ...) {
                      cell.xlim = get.cell.meta.data("cell.xlim")
                      cell.ylim = get.cell.meta.data("cell.ylim")
                      for(j in 1:9) {
                        y = cell.ylim[1] + (cell.ylim[2]-cell.ylim[1])/10*j
                        circos.lines(cell.xlim, c(y, y), col = "#FFFFFF", lwd = 0.3)
                      }
                      circos.genomicRect(region, value, ytop = 0, ybottom = value[,1], col = value[,2], 
                                         border = NA, ...)
                      #circos.genomicText(region, value, y = 0.3, labels = value[,1], ...)
                    })
circos.clear()
#????Ȧͼ?м???ͼ??
middle.legend = Legend(
  labels = c('Number of Genes','Number of Select','Rich Factor(0-1)'),
  type="points",pch=c(15,15,17),legend_gp = gpar(col=c('pink','#BA55D3',ontology.col[1])),
  title="",nrow=3,size= unit(3, "mm")
)
circle_size = unit(1, "snpc")
draw(middle.legend,x=circle_size*0.42)
#????GO??????ͼ??
main.legend = Legend(
  labels = c("Biological Process","Cellular Component", "Molecular Function"),  type="points",pch=15,
  legend_gp = gpar(col=ontology.col), title_position = "topcenter",
  title = "ONTOLOGY", nrow = 3,size = unit(3, "mm"),grid_height = unit(5, "mm"),
  grid_width = unit(5, "mm")
)
#???Ƹ?????????pvalue??ͼ??
logp.legend = Legend(
  labels=c('(0,2]','(2,4]','(4,6]','(6,8]','(8,10]','(10,15]','(15,20]','>=20'),
  type="points",pch=16,legend_gp=gpar(col=logpvalue.col),title="-log10(Pvalue)",
  title_position = "topcenter",grid_height = unit(5, "mm"),grid_width = unit(5, "mm"),
  size = unit(3, "mm")
)
lgd = packLegend(main.legend,logp.legend)
circle_size = unit(1, "snpc")
print(circle_size)
draw(lgd, x = circle_size*0.85, y=circle_size*0.55,just = "left")
dev.off()
```
```{r}
############### 数据处理 ############## 
# 载入R包： 
library(GOplot)

# 示例数据：
data(EC)
class(EC)
dim(EC$david)
dim(EC$genelist)
```
```{r}
head(EC$david)
```

```{r}
david <- data.frame(kk)
david <- david[,c(1:3,7,9)]
david$geneID <- gsub("/",",",david$geneID)
colnames(david)<-c(  'Category','ID','Term',"adj_pval",'Genes')
head(david)
```

```{r}
head(EC$genelist)
```
```{r}
genelist <- data.frame(ID=rownames(DEG),logFC = DEG$log2FoldChange)
head(genelist)
```

```{r}
# 将上述两个数据结合：
circ <- circle_dat(david,genelist)


# labels:设置标签显示的阈值。阈值是指-log(adj_Pvalue) -- 默认值=5
# 简单的理解就是：看y轴，这个值以上的圈圈保留：
pdf("Figure2/GOBubble1_up.pdf", height = 8, width = 10)
GOBubble(circ, labels = 4)
dev.off()

############### 分面气泡图 ############## 
# 略调整参数之后可以对图的布局、颜色等进行调整：
pdf("./Figure2/GOBubble2_up.pdf", height = 10, width = 15)
GOBubble(circ, title = 'Bubble plot',  # 标题
         colour = c('#e6b707', '#99c355', '#4cace9'),  # 气泡颜色
         display = 'multiple', # 表示分面
         labels = 3)
dev.off()

# 背景着色：
pdf("Figure2/GOBubble3_up.pdf", height = 10, width = 15)
GOBubble(circ, title = 'Bubble plot',  # 标题
         colour = c('#e6b707', '#99c355', '#4cace9'),  # 气泡颜色
         display = 'multiple', # 表示分面
         labels = 3,
         bg.col = T  # 背景着色，按照点的颜色分配背景色
         )
dev.off()

############## 进阶版：用ggplot2绘制类似的气泡图 ##################
library(ggplot2)
library(RColorBrewer)
library(ggrepel)

# 剔除一些重复的GO ID：
circ2<-circ[!duplicated(circ$ID),-5]

ggplot(circ2, aes(x = zscore, y = -log10(adj_pval))) +
  geom_point(aes(size = count,color=category),alpha = 0.6) +
  scale_size(range = c(1,12)) +
  # scale_color_brewer(palette = "Set1") +
  scale_color_manual(values = c('#e6b707', '#99c355', '#4cace9')) +  # Manual color values
  theme_bw() +
  geom_text_repel(
    data = circ2[-log10(circ2$adj_pval) > 3,],
    aes(label = ID),
    size = 3,
    segment.color = "black", show.legend = FALSE )
ggsave("Figure2/GOBubble_ggplot1_up.pdf", height = 7, width = 7)

############## 分面 ##################
ggplot(circ2, aes(x = zscore, y = -log10(adj_pval))) +
  geom_point(aes(size = count, color=category), alpha = 0.6) +
  scale_size(range =c (1, 12)) +
  # scale_color_brewer(palette = "Set1") +
    scale_color_manual(values = c('#e6b707', '#99c355', '#4cace9')) +  # Manual color values
  theme_bw() +
  theme(legend.position = c("none")) +
  geom_text_repel(
    data = circ2[-log10(circ2$adj_pval) > 3,],
    aes(label = ID),
    size = 3,
    segment.color = "black", show.legend = FALSE ) +
  facet_grid(.~category)

ggsave("Figure2/GOBubble_ggplot2_up.pdf", height = 5, width = 8)
```


# DOWNGENE
```{r}
rt <- deg_down
genes <- unique(as.vector(rownames(rt)))
entrezIDs=mget(genes, org.Hs.egSYMBOL2EG, ifnotfound=NA)
entrezIDs=as.character(entrezIDs)
gene=entrezIDs[entrezIDs!="NA"]        #ȥ??????idΪNA?Ļ???
#gene=gsub("c\\(\"(\\d+)\".*", "\\1", gene)
#GO????????
kk=enrichGO(gene=gene, OrgDb="org.Hs.eg.db", pvalueCutoff=0.1, qvalueCutoff=1, ont="all", readable=T)
GO=as.data.frame(kk)
GO=GO[(GO$pvalue<pvalueFilter & GO$qvalue<qvalueFilter),]
#?????????????Ľ???
write.table(GO, file="data/GO_DOWN.txt", sep="\t", quote=F, row.names = F)
```

```{r}
pdf(file="Figure2/barplot_down.pdf", width=14, height=7)
bar=barplot(kk, drop=TRUE, showCategory=10, label_format=130, split="ONTOLOGY", color=colorSel) + facet_grid(ONTOLOGY~., scale='free')
print(bar)
dev.off()
		
#????ͼ
pdf(file="Figure2/bubble_down.pdf", width=14, height=7)
bub=dotplot(kk, showCategory=10, orderBy="GeneRatio", label_format=130, split="ONTOLOGY", color=colorSel) + facet_grid(ONTOLOGY~., scale='free')
print(bub)
dev.off()
```
```{r}
############## 富集分析分组柱状图 ##################
library(dplyr)
ego <- kk

# 先根据BP、CC和MF按照q值选出前10个GO出来用于画图：用by实现
ego_filter <- by(ego, ego$ONTOLOGY, function(x) arrange(x, x[,8])[1:10,])
ego <- rbind(ego_filter$BP,ego_filter$CC,ego_filter$MF)

# 将数据按照ONTOLOGY分组，并按gene数目排序：
bp <- ego[which(ego$ONTOLOGY %in% "BP"),]
newbp <- arrange(bp, bp[,10])

cc <- ego[which(ego$ONTOLOGY %in% "CC"),]
newcc <- arrange(cc, cc[,10])

mf <- ego[which(ego$ONTOLOGY %in% "MF"),]
newmf <- arrange(mf, mf[,10])

go_enrich_df <- rbind(newbp,newcc,newmf)

# 如果我们熟练掌握apply系列函数的话，上面的过程完全可以用by快速实现；
go_list <- by(ego, ego$ONTOLOGY, function(x) arrange(x, x[,10]))
go_enrich_df2 <- rbind(go_list$BP,go_list$CC,go_list$MF)

go_enrich_df$number <- factor(rev(1:nrow(go_enrich_df)))

shorten_names <- function(x, n_word=10, n_char=40){
   if (length(strsplit(x, " ")[[1]]) > n_word || (nchar(x)>n_char))
     {
           if (nchar(x) >n_char) x <- substr(x, 1, n_char)
           x <- paste(paste(strsplit(x, " ")[[1]][1:min(length(strsplit(x," ")[[1]]), n_word)],
                                                                                collapse=" "), "...", sep="")
           return(x)
         } 
   else
     {
           return(x)
         }
}

# labels=(sapply(
#    levels(go_enrich_df$Description)[as.numeric(go_enrich_df$Description)],
#    shorten_names))

labels <- (sapply(
  go_enrich_df$Description,shorten_names
))

labels
```


```{r}
# 排序：
#  rev(1:nrow(go_enrich_df)) 的作用是生成一个逆序的序列，范围从 1 到 go_enrich_df 数据框的行数。换句话说，它创建了一个从 go_enrich_df 的最后一行到第一行的递减序列。
names(labels) = rev(1:nrow(go_enrich_df))
CPCOLS <- c('#e6b707', '#99c355', '#4cace9')

library(ggplot2)

# 垂直版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_bar(stat="identity", width=0.8) + coord_flip() + 
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text=element_text(face = "plain"))+
  theme(axis.text.y=element_text(color=rep(rev(CPCOLS),rep(10,3)))) + 
  theme(legend.title=element_blank())

ggsave("./Figure2/vetical_GO_plot_down.pdf", height = 10,width = 8)

# 水平版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_bar(stat="identity", width=0.8) +
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text =element_text(face = "plain")) + 
  theme(axis.text.x=element_text(angle=70, hjust = 1, color=rep(rev(CPCOLS),rep(10,3)))) + 
  theme(legend.title=element_blank(),legend.position = "top")

ggsave("./Figure2/horizontal_GO_plot_down.pdf", height = 6.5,width = 10)

################# 同样也可以绘制分组气泡图 ##################3
# 垂直版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_point(aes(size=-log10(qvalue)), shape=21, stat="identity") + coord_flip() + 
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text=element_text(face = "plain"))+
  theme(axis.text.y=element_text(color=rep(rev(CPCOLS),rep(10,3)))) + 
  theme(legend.title=element_blank())

ggsave("Figure2/vetical_GO_buble_plot_down.pdf", height = 10,width = 8)

# 水平版本：
ggplot(data=go_enrich_df, aes(x=number, y=Count, fill=ONTOLOGY)) +
  geom_point(aes(size=-log10(qvalue)), shape=21, stat="identity") +
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("GO term") + ylab("Num of Genes") + 
  theme(axis.text =element_text(face = "plain")) + 
  theme(axis.text.x=element_text(angle=70, hjust = 1, color=rep(rev(CPCOLS),rep(10,3)))) + 
  guides(size=guide_legend("-log10(qvalue)"),
                 fill=guide_legend("ONTOLOGY"))+
  theme(legend.text = element_text(vjust = 0.5))

ggsave("Figure2/horizontal_GO_buble_plot_down.pdf", height = 6.5,width = 10)
```


```{r}
###########????GOȦͼ###########
ontology.col=c('#e6b707', '#99c355', '#4cace9')
data=GO[order(GO$p.adjust),]
datasig=data[data$pvalue<0.05,,drop=F]
BP = datasig[datasig$ONTOLOGY=="BP",,drop=F]
CC = datasig[datasig$ONTOLOGY=="CC",,drop=F]
MF = datasig[datasig$ONTOLOGY=="MF",,drop=F]
BP = head(BP,6)
CC = head(CC,6)
MF = head(MF,6)
data = rbind(BP,CC,MF)
main.col = ontology.col[as.numeric(as.factor(data$ONTOLOGY))]

#????Ȧͼ????
BgGene = as.numeric(sapply(strsplit(data$BgRatio,"/"),'[',1))
Gene = as.numeric(sapply(strsplit(data$GeneRatio,'/'),'[',1))
ratio = Gene/BgGene
logpvalue = -log(data$pvalue,10)
logpvalue.col = brewer.pal(n = 8, name = "Reds")
f = colorRamp2(breaks = c(0,2,4,6,8,10,15,20), colors = logpvalue.col)
BgGene.col = f(logpvalue)
df = data.frame(GO=data$ID,start=1,end=max(BgGene))
rownames(df) = df$GO
bed2 = data.frame(GO=data$ID,start=1,end=BgGene,BgGene=BgGene,BgGene.col=BgGene.col)
bed3 = data.frame(GO=data$ID,start=1,end=Gene,BgGene=Gene)
bed4 = data.frame(GO=data$ID,start=1,end=max(BgGene),ratio=ratio,col=main.col)
bed4$ratio = bed4$ratio/max(bed4$ratio)*9.5

#????Ȧͼ?????岿??
pdf(file="Figure2/GO.circlize_down.pdf", width=10, height=10)
par(omi=c(0.1,0.1,0.1,1.5))
circos.par(track.margin=c(0.01,0.01))
circos.genomicInitialize(df,plotType="none")
circos.trackPlotRegion(ylim = c(0, 1), panel.fun = function(x, y) {
  sector.index = get.cell.meta.data("sector.index")
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  circos.text(mean(xlim), mean(ylim), sector.index, cex = 0.8, facing = "bending.inside", niceFacing = TRUE)
}, track.height = 0.08, bg.border = NA,bg.col = main.col)

for(si in get.all.sector.index()) {
  circos.axis(h = "top", labels.cex = 0.6, sector.index = si,track.index = 1,
              major.at=seq(0,max(BgGene),by=100),labels.facing = "clockwise")
}
f = colorRamp2(breaks = c(-1, 0, 1), colors = c("green", "black", "red"))
circos.genomicTrack(bed2, ylim = c(0, 1),track.height = 0.1,bg.border="white",
                    panel.fun = function(region, value, ...) {
                      i = getI(...)
                      circos.genomicRect(region, value, ytop = 0, ybottom = 1, col = value[,2], 
                                         border = NA, ...)
                      circos.genomicText(region, value, y = 0.4, labels = value[,1], adj=0,cex=0.8,...)
                    })
circos.genomicTrack(bed3, ylim = c(0, 1),track.height = 0.1,bg.border="white",
                    panel.fun = function(region, value, ...) {
                      i = getI(...)
                      circos.genomicRect(region, value, ytop = 0, ybottom = 1, col = '#BA55D3', 
                                         border = NA, ...)
                      circos.genomicText(region, value, y = 0.4, labels = value[,1], cex=0.9,adj=0,...)
                    })
circos.genomicTrack(bed4, ylim = c(0, 10),track.height = 0.35,bg.border="white",bg.col="grey90",
                    panel.fun = function(region, value, ...) {
                      cell.xlim = get.cell.meta.data("cell.xlim")
                      cell.ylim = get.cell.meta.data("cell.ylim")
                      for(j in 1:9) {
                        y = cell.ylim[1] + (cell.ylim[2]-cell.ylim[1])/10*j
                        circos.lines(cell.xlim, c(y, y), col = "#FFFFFF", lwd = 0.3)
                      }
                      circos.genomicRect(region, value, ytop = 0, ybottom = value[,1], col = value[,2], 
                                         border = NA, ...)
                      #circos.genomicText(region, value, y = 0.3, labels = value[,1], ...)
                    })
circos.clear()
#????Ȧͼ?м???ͼ??
middle.legend = Legend(
  labels = c('Number of Genes','Number of Select','Rich Factor(0-1)'),
  type="points",pch=c(15,15,17),legend_gp = gpar(col=c('pink','#BA55D3',ontology.col[1])),
  title="",nrow=3,size= unit(3, "mm")
)
circle_size = unit(1, "snpc")
draw(middle.legend,x=circle_size*0.42)
#????GO??????ͼ??
main.legend = Legend(
  labels = c("Biological Process","Cellular Component", "Molecular Function"),  type="points",pch=15,
  legend_gp = gpar(col=ontology.col), title_position = "topcenter",
  title = "ONTOLOGY", nrow = 3,size = unit(3, "mm"),grid_height = unit(5, "mm"),
  grid_width = unit(5, "mm")
)
#???Ƹ?????????pvalue??ͼ??
logp.legend = Legend(
  labels=c('(0,2]','(2,4]','(4,6]','(6,8]','(8,10]','(10,15]','(15,20]','>=20'),
  type="points",pch=16,legend_gp=gpar(col=logpvalue.col),title="-log10(Pvalue)",
  title_position = "topcenter",grid_height = unit(5, "mm"),grid_width = unit(5, "mm"),
  size = unit(3, "mm")
)
lgd = packLegend(main.legend,logp.legend)
circle_size = unit(1, "snpc")
print(circle_size)
draw(lgd, x = circle_size*0.85, y=circle_size*0.55,just = "left")
dev.off()
```

```{r}
david <- data.frame(kk)
david <- david[,c(1:3,7,9)]
david$geneID <- gsub("/",",",david$geneID)
colnames(david)<-c(  'Category','ID','Term',"adj_pval",'Genes')
genelist <- data.frame(ID=rownames(DEG),logFC = DEG$log2FoldChange)
# 将上述两个数据结合：
circ <- circle_dat(david,genelist)

############## 进阶版：用ggplot2绘制类似的气泡图 ##################
library(ggplot2)
library(RColorBrewer)
library(ggrepel)

# 剔除一些重复的GO ID：
circ2<-circ[!duplicated(circ$ID),-5]

ggplot(circ2, aes(x = zscore, y = -log10(adj_pval))) +
  geom_point(aes(size = count,color=category),alpha = 0.6) +
  scale_size(range = c(1,12)) +
  # scale_color_brewer(palette = "Set1") +
  scale_color_manual(values = c('#e6b707', '#99c355', '#4cace9')) +  # Manual color values
  theme_bw() +
  geom_text_repel(
    data = circ2[-log10(circ2$adj_pval) > 2,],
    aes(label = ID),
    size = 3,
    segment.color = "black", show.legend = FALSE )
ggsave("Figure2/GOBubble_ggplot1_down.pdf", height = 7, width = 7)

############## 分面 ##################
ggplot(circ2, aes(x = zscore, y = -log10(adj_pval))) +
  geom_point(aes(size = count, color=category), alpha = 0.6) +
  scale_size(range =c (1, 12)) +
  # scale_color_brewer(palette = "Set1") +
    scale_color_manual(values = c('#e6b707', '#99c355', '#4cace9')) +  # Manual color values
  theme_bw() +
  theme(legend.position = c("none")) +
  geom_text_repel(
    data = circ2[-log10(circ2$adj_pval) > 2,],
    aes(label = ID),
    size = 3,
    segment.color = "black", show.legend = FALSE ) +
  facet_grid(.~category)

ggsave("Figure2/GOBubble_ggplot2_down.pdf", height = 5, width = 8)
```

