```{r}
rm(list=ls()) #清除工作区
library(ggplot2)
## 可以先尝试使用merge.prenorm，去批次前的诊断模型说服力最好！！
## 如果roc不理想，则使用merge.normalzie！
## 先试下面
# rt=read.table('merge.preNorm.txt', header=T, sep="\t", check.names=F, row.names=1)
## 再试下面
rt=read.table('./data/merge.normalize.txt', header=T, sep="\t", check.names=F, row.names=1)
intersect_gene <- read.table("data/intersect_gene.txt")
intersect_gene <- intersect_gene$V1
rt=rt[intersect_gene,]

group_list1=c(rep('CT',3),rep('PC',3))
group_list2=c(rep('CT',4),rep('PC',4))
group_list3=c(rep('CT',3),rep('PC',3))
group_list4=c(rep('PC',5),rep('CT',5))
## train
a = grep('GSE138518',colnames(rt))
b = grep('GSE155489',colnames(rt))
c = grep('GSE193123',colnames(rt))
d= grep('GSE168404',colnames(rt))
## 训练集
X_train=t(rt[,c(a,b,c)])
group_list_train=c(group_list1,group_list2,group_list3)
group_list_train=factor(group_list_train,levels=c('CT','PC'))
```



```{r}
# 生成模拟数据
Group <- rep(c("group1","group2"),each=200) #组别变量
Group <- factor(Group) #组别因子化
Attribute <- c(rep("Attribute_1",100),rep("Attribute_2",100),rep("Attribute_1",100),rep("Attribute_2",100)) #每个组别的两个属性
Attribute <- factor(Attribute) #属性因子化
value <- c(rnorm(100)+1,rnorm(100)+2,rnorm(100)+1.2,rnorm(100)+1.5) #随机赋值

Data <- data.frame(Group=Group,Attribute=Attribute,value=value) #生成数据框

```

```{r}
Data <- data.frame(X_train)
Data$Group <- group_list_train
Data <- Data[,c(1,5)]
colnames(Data) <- c("value","Group")

```
```{r}
library("ggstatsplot")
library("ggplot2")
```
```{r}
#ggbetweenstats(),用于绘制组间比较的箱线图、小提琴图及小提琴箱线组合图，并提供详细的参数检验和统计信息
p1 <- ggbetweenstats(
  data  = Data,
  x     = Group,
  y     = value,
  plot.type = "box",#图标类型，不加参数则默认为boxviolin，其它可选为：box、violin
  title = "ACSS2"
)
p1#上述为ggbetweenstats()的最简单函数调用
```
```{r}
#部分可视化有关的参数：
p2 <- ggbetweenstats(
  data  = Data,
  x     = Group,
  y     = value,
  plot.type = "boxviolin",
  title = "Distribution of sepal length across Iris species",
  results.subtitle = TRUE,#决定是否将统计检验的结果显示为副标题（默认TRUE）;如果设置为FALSE,则仅返回绘图
  subtitle = NULL,#副标题,默认显示统计检验结果,自定义则results.subtitle=FALSE
  outlier.tagging = TRUE,#是否标记离群异常值，默认FALSE
  outlier.shape = 19,#异常值形状,可设置为NA将其隐藏（不是删除，因此不会影响统计检验结果）
  outlier.color = "pink",#异常值颜色
  outlier.label.args = list(size = 4),#异常值标签大小
  point.args = list(position = ggplot2::position_jitterdodge(dodge.width = 0.6),
  alpha = 0.5, size = 3, stroke = 0),#传递给geom_point的参数设置
  violin.args = list(width = 0.4, alpha = 0.2),#传递给geom_violin的参数设置
  ggtheme = theme_bw(),#主题修改，可直接调用ggplot2的主题，默认主题为ggstatsplot::theme_ggstatsplot()
  package = "ggsci",#提取调色板所需的包
  palette = "uniform_startrek"#选择提取包中的调色板
)
p2
```
```{r}
#ggwithinstats()用于绘制组内比较的小提琴箱线组合图
#此函数为ggbetweenstats()的孪生函数，行为方式也基本相同。绘图结构之间区别在于在组与组均值之间通过路径连接来突出数据间彼此配对
# install.packages("afex")
library(afex) #to run anova
Data <- data.frame(X_train)
Data$Group <- group_list_train
Data <- Data[,c(1,5)]
colnames(Data) <- c("value","Group")

p3 <- ggwithinstats(
  data  = Data,
  x     = Group,
  y     = value,
  title = "ACSS2",
  type = "p", ## parametric
  pairwise.display = "significant",
)
p3
```




```{r}
Data <- data.frame(X_train)
Data$Group <- group_list_train
Data <- Data[,c(2,5)]
colnames(Data) <- c("value","Group")
p4 <- ggwithinstats(
  data  = Data,
  x     = Group,
  y     = value,
  title = "LPIN2",
  type = "p", ## parametric
  pairwise.display = "significant"
)
p4
```
```{r}
Data <- data.frame(X_train)
Data$Group <- group_list_train
Data <- Data[,c(3,5)]
colnames(Data) <- c("value","Group")
p5 <- ggwithinstats(
  data  = Data,
  x     = Group,
  y     = value,
  title = "NR4A1",
  type = "p", ## parametric
  pairwise.display = "significant"
)
p5
```
```{r}
Data <- data.frame(X_train)
Data$Group <- group_list_train
Data <- Data[,c(4,5)]
colnames(Data) <- c("value","Group")
p6 <- ggwithinstats(
  data  = Data,
  x     = Group,
  y     = value,
  title = "CYBB",
  type = "p", ## parametric
  pairwise.display = "significant"
)
p6
```
```{r}
#合并p4、p5、p6：
combine_plots(
  list(p3,p4, p5, p6),
  plotgrid.args = list(nrow = 1),
  annotation.args = list(
  title = "VIOLIN",
  caption = "VIOLIN"
  )
)
```






