```{r}
load("./data/DESeq2_raw.Rdata")
dim(DEG)
```

```{r}
DEG$g=ifelse(DEG$pvalue>0.05,'stable', 
            ifelse( DEG$log2FoldChange >1,'up', 
                    ifelse( DEG$log2FoldChange < -1,'down','stable') )
)
table(DEG$g)
```


```{r}
deg_up <- DEG[DEG$g=="up",]
deg_down <- DEG[DEG$g=="down",]
```

# UPGENE
```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(org.Rn.eg.db)
library(enrichplot)
library(ggplot2)
library(circlize)
library(RColorBrewer)
library(dplyr)
library(ComplexHeatmap)

pvalueFilter=0.05     #pֵ????????
qvalueFilter=1        #????????pֵ????????
inputFile="interGenes.txt"     #???????????б??ļ?

#????ͼ?ε???ɫ
colorSel="qvalue"
if(qvalueFilter>0.05){
	colorSel="pvalue"
}
	
rt <- deg_up
genes <- unique(as.vector(rownames(rt)))
entrezIDs=mget(genes, org.Hs.egSYMBOL2EG, ifnotfound=NA)
entrezIDs=as.character(entrezIDs)
gene=entrezIDs[entrezIDs!="NA"]        #ȥ??????idΪNA?Ļ???
#gene=gsub("c\\(\"(\\d+)\".*", "\\1", gene)
```


```{r}
#KEGG????????
kk <- enrichKEGG(gene=gene, organism="hsa", pvalueCutoff=1, qvalueCutoff=1)
kk@result$Description=gsub(" - Homo sapiens \\(human\\)", "", kk@result$Description)
KEGG=as.data.frame(kk)
KEGG$geneID=as.character(sapply(KEGG$geneID,function(x)paste(rt$genes[match(strsplit(x,"/")[[1]],as.character(rt$entrezID))],collapse="/")))
KEGG=KEGG[(KEGG$pvalue<pvalueFilter & KEGG$qvalue<qvalueFilter),]
#?????????????Ľ???
write.table(KEGG, file="data/KEGG_UP.txt", sep="\t", quote=F, row.names = F)

#??????ʾͨ·????Ŀ
showNum=30     #??ʾ????????????ǰ30??ͨ·
if(nrow(KEGG)<showNum){
	showNum=nrow(KEGG)
}

#??״ͼ
pdf(file="Figure2/KEGGbarplot_up.pdf", width=8.5, height=7)
barplot(kk, drop=TRUE, showCategory=showNum, label_format=130, color=colorSel)
dev.off()

#????ͼ
pdf(file="Figure2/KEGGbubble_up.pdf", width=8.5, height=7)
dotplot(kk, showCategory=showNum, orderBy="GeneRatio", label_format=130, color=colorSel)
dev.off()


######Video source: https://ke.biowolf.cn
######??????ѧ??: https://www.biowolf.cn/
######΢?Ź??ںţ?biowolf_cn
######???????䣺biowolf@foxmail.com
######????΢??: 18520221056
```
```{r}

# 美化版本的富集条形图 -----------------------------------------------------------
library(ggplot2)
library(tidyr)
mytheme1 <- theme_classic()+
  theme(axis.title.y=element_text(size = 13,face = "bold",color="black"),
        axis.title.x=element_text(size = 15,face = "bold",color="black"),
        axis.text.y=element_text(size = 14,face='bold',color="black"),
        axis.text.x=element_text(size = 15,face='bold',color="black"),
        axis.title=element_text(size = 15,face="bold",color="black"),
        text=element_text(family = "Arial"),
        panel.grid.major = element_blank(),
        panel.grid.minor  = element_blank(),
        plot.title = element_text(size = 17, face = "bold"),
        plot.subtitle = element_text(size = 7),
        legend.title = element_text(size=12,face = "bold"),
        legend.text = element_text(size=12,face = "bold"))


## 提取top30的通路
KEGG_top30 <- kk@result[1:30,]

## 计算GeneRatio，先将GeneRatio分成两个字段，计算比值
KEGG_top30  <- separate(KEGG_top30,col="GeneRatio",into=c("count","pathway_count"),sep="[/]",remove=T)
KEGG_top30$count <- as.numeric(KEGG_top30$count)
KEGG_top30$pathway_count <- as.numeric(KEGG_top30$pathway_count)
KEGG_top30$GeneRatio <- round(KEGG_top30$count/KEGG_top30$pathway_count,2)

## 绘制
KEGG_top30$Description <- factor(KEGG_top30$Description,levels = rev(KEGG_top30$Description))

ggplot(data = KEGG_top30,aes(x = Count,y = Description,fill = -log10(pvalue)))+
  scale_fill_distiller(palette = "RdPu",direction = 1) + ##颜色可以调整
  geom_bar(stat = "identity",width = 0.8) +
  labs(x = "GeneRatio",y = "",title = "Top 30 enriched KEGG pathways",size = "Count") +
  mytheme1
```

```{r}

# 美化版本的富集气泡图 -----------------------------------------------------------
## 提取top30的通路
KEGG_top30 <- kk@result[1:30,]
## 计算GeneRatio，先将GeneRatio分成两个字段，计算比值
KEGG_top30  <- separate(KEGG_top30,col="GeneRatio",into=c("count","pathway_count"),sep="[/]",remove=T)
KEGG_top30$count <- as.numeric(KEGG_top30$count)
KEGG_top30$pathway_count <- as.numeric(KEGG_top30$pathway_count)
KEGG_top30$GeneRatio <- round(KEGG_top30$count/KEGG_top30$pathway_count,2)

## 绘制
ggplot(data = KEGG_top30,
  aes(x = GeneRatio,y = reorder(Description,GeneRatio)))+  # 用reorder将pathway按照GeneRatio重排
  geom_point(aes(size = Count,color = -log10(pvalue)))+
  scale_color_distiller(palette = "Spectral",direction = 1) +
  labs(x = "GeneRatio",y = "",title = "Top 30 enriched KEGG pathways",size = "Count") +
  mytheme1

```

# DOWNGENE
```{r}
rt <- deg_down
genes <- unique(as.vector(rownames(rt)))
entrezIDs=mget(genes, org.Hs.egSYMBOL2EG, ifnotfound=NA)
entrezIDs=as.character(entrezIDs)
gene=entrezIDs[entrezIDs!="NA"]        #ȥ??????idΪNA?Ļ???
#gene=gsub("c\\(\"(\\d+)\".*", "\\1", gene)

#KEGG????????
kk <- enrichKEGG(gene=gene, organism="hsa", pvalueCutoff=1, qvalueCutoff=1)
kk@result$Description=gsub(" - Homo sapiens \\(human\\)", "", kk@result$Description)
KEGG=as.data.frame(kk)
KEGG$geneID=as.character(sapply(KEGG$geneID,function(x)paste(rt$genes[match(strsplit(x,"/")[[1]],as.character(rt$entrezID))],collapse="/")))
KEGG=KEGG[(KEGG$pvalue<pvalueFilter & KEGG$qvalue<qvalueFilter),]
#?????????????Ľ???
write.table(KEGG, file="data/KEGG_DOWN.txt", sep="\t", quote=F, row.names = F)

#??????ʾͨ·????Ŀ
showNum=30     #??ʾ????????????ǰ30??ͨ·
if(nrow(KEGG)<showNum){
	showNum=nrow(KEGG)
}

#??״ͼ
pdf(file="Figure2/KEGGbarplot_down.pdf", width=8.5, height=7)
barplot(kk, drop=TRUE, showCategory=showNum, label_format=130, color=colorSel)
dev.off()

#????ͼ
pdf(file="Figure2/KEGGbubble_down.pdf", width=8.5, height=7)
dotplot(kk, showCategory=showNum, orderBy="GeneRatio", label_format=130, color=colorSel)
dev.off()
```
```{r}
## 提取top30的通路
KEGG_top30 <- kk@result[1:30,]

## 计算GeneRatio，先将GeneRatio分成两个字段，计算比值
KEGG_top30  <- separate(KEGG_top30,col="GeneRatio",into=c("count","pathway_count"),sep="[/]",remove=T)
KEGG_top30$count <- as.numeric(KEGG_top30$count)
KEGG_top30$pathway_count <- as.numeric(KEGG_top30$pathway_count)
KEGG_top30$GeneRatio <- round(KEGG_top30$count/KEGG_top30$pathway_count,2)

## 绘制
KEGG_top30$Description <- factor(KEGG_top30$Description,levels = rev(KEGG_top30$Description))

ggplot(data = KEGG_top30,aes(x = Count,y = Description,fill = -log10(pvalue)))+
  scale_fill_distiller(palette = "RdPu",direction = 1) + ##颜色可以调整
  geom_bar(stat = "identity",width = 0.8) +
  labs(x = "GeneRatio",y = "",title = "Top 30 enriched KEGG pathways",size = "Count") +
  mytheme1
```

```{r}
# 美化版本的富集气泡图 -----------------------------------------------------------
## 提取top30的通路
KEGG_top30 <- kk@result[1:30,]
## 计算GeneRatio，先将GeneRatio分成两个字段，计算比值
KEGG_top30  <- separate(KEGG_top30,col="GeneRatio",into=c("count","pathway_count"),sep="[/]",remove=T)
KEGG_top30$count <- as.numeric(KEGG_top30$count)
KEGG_top30$pathway_count <- as.numeric(KEGG_top30$pathway_count)
KEGG_top30$GeneRatio <- round(KEGG_top30$count/KEGG_top30$pathway_count,2)

## 绘制
ggplot(data = KEGG_top30,
  aes(x = GeneRatio,y = reorder(Description,GeneRatio)))+  # 用reorder将pathway按照GeneRatio重排
  geom_point(aes(size = Count,color = -log10(pvalue)))+
  scale_color_distiller(palette = "Spectral",direction = 1) +
  labs(x = "GeneRatio",y = "",title = "Top 30 enriched KEGG pathways",size = "Count") +
  mytheme1
```

