WE NEED USE CLUSTERPROFILER WITH GSEA/GSEGO/GSEKEGG

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
```
```{r}
# loda genelist
data(geneList, package="DOSE")
head(geneList)
```
The data format required to do GSEA analysis, as mentioned earlier, needs to be an ordered numerical vector whose name is the ID of the gene
```{r}
load("./data/DESeq2_raw.Rdata")
dim(DEG)
DEG$genesymbol <- rownames(DEG)
```
```{r}
gene_entrezid <- bitr(geneID = DEG$genesymbol
                         , fromType = "SYMBOL" # 从symbol
                         , toType = "ENTREZID" # 转成ENTREZID
                         , OrgDb = "org.Hs.eg.db"
                         )
head(gene_entrezid)
```
```{r}
gene_entrezid <- merge(gene_entrezid,DEG,by.x = "SYMBOL", by.y = "genesymbol")
genelist <- gene_entrezid$log2FoldChange
names(genelist) <- gene_entrezid$ENTREZID
genelist <- sort(genelist,decreasing = T)
head(genelist)
```


```{r}
geneList <- genelist
##### gsea富集 ####
eke <- gseKEGG(geneList     = geneList,
                   organism     = "hsa", #人hsa 鼠mmu
                   pvalueCutoff = 0.05)  #实际为padj阈值可调整

KEGG <- DOSE::setReadable(eke, 
                             OrgDb=org.Hs.eg.db,
                             keyType='ENTREZID')#转化id 

ego <- gseGO(geneList     = geneList,
              OrgDb        = org.Hs.eg.db, #人类org.Hs.eg.db 鼠org.Mm.eg.db
              ont          = "ALL", # "BP"、"MF"和"CC"或"ALL"
              minGSSize    = 100,
              maxGSSize    = 500,
              pvalueCutoff = 0.05, #实际为padj阈值可调整
              verbose      = FALSE)
 
GO <- DOSE::setReadable(ego, 
                           OrgDb=org.Hs.eg.db,
                           keyType='ENTREZID')#转化id 
save(KEGG, GO, file = "./data/GSEA_result.RData")
```

```{r}
GO_result <- data.frame(GO)
KEGG_result <- data.frame(KEGG)
write.table(GO_result, file="data/GO_GSEA.txt", sep="\t", quote=F, row.names = F)
write.table(KEGG_result, file="data/KEGG_GSEA.txt", sep="\t", quote=F, row.names = F)
```


show each top 10 terms:
```{r}
library(PDtools)
# default plot
# free scale
dotplotGsea(data = GO,topn = 10,
            order.by = 'NES',
            add.seg = T,
            scales = 'free')
```

```{r}
# free scale
dotplotGsea(data = KEGG,topn = 10,
            order.by = 'NES',
            add.seg = T,
            scales = 'free')
```

```{r}
gseaNb(object = KEGG,
       geneSetID = 'hsa05417',
       subPlot = 2,
       addGene = T,
       kegg = T,
       markTopgene = T)
```
```{r}
gseaNb(object = KEGG,
       geneSetID = 'hsa04072',
       subPlot = 2,
       addGene = T,
       kegg = T,
       markTopgene = T)
```
```{r}
# retain curve and heatmap
gseaNb(object = GO,
       geneSetID = 'GO:0032496',
       subPlot = 2,
       addPval = T,
       pvalX = 0.85,pvalY = 0.75)
```

```{r}
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
sortkk<-GO[order(GO$enrichmentScore,decreasing=T)]
gseaplot2(GO, geneSetID = row.names(sortkk)[1:5],base_size = 10)
```

